== Introduction

===	Scope

GeoPackage is an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information.

Over the course of 2017 and 2018, the GeoPackage Standards Working Group (SWG) made a number of changes to the GeoPackage Encoding Standard Version 1.2 (OGC 12-128r14). These changes have been aggregated into version 1.2.1 of the GeoPackage Encoding Standard (12-128r14). 

GeoPackage 1.2.1 is a corrigendum revision to version 1.2.0. The corrigendum revision designation is being used because none of the changes alter conformance requirements. However, all of these changes were carefully considered for impact on existing implementations. Changes that were considered to have a significant impact were rejected or recast in order to limit their impact. 

All changes were all managed via the GeoPackage GitHub repository. All substantive issues and most administrative issues were raised in the GitHub Issue Tracker and discussed by the SWG. Once the issue was resolved, a pull request was generated and merged into the repository. Some administrative issues such as typos were corrected directly through a commit on the master branch.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:


.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Jeff Yutzler | Image Matters
|====================


=== Future Work
No future work is planned to this document.

// *****************************************************************************
// please don't change the foreword
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
