== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard [OGC 06-121r9] (( and in OGC® Abstract Specification Topic TBD: TBD )) shall apply. In addition, the following terms and definitions apply.

===	administrative change
An administrative change is a change that does not alter the abstract tests for any requirements. It includes typographical errors, changes in wording to improve clarity or consistency, and perfunctory changes like changes in version numbers. 

=== critical Change
A critical change is a change that alters requirements in a way that is known to cause reverse compatibility issues. 

=== substantive change
A substantive change is a change that alters requirements in a way that is not deemed to have a high risk for causing reverse compatibility issues.

===	Abbreviated terms

* CRS Coordinate Reference System
* DDL Database Definition Language
* GPKG GeoPackage
* SQL Structured Query Language
* SWG Standards Working Group
* WKT Well Known Text
